### ISSUE TITLE
name of conda package

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima-camera-photonicscience#1]
Hello there,
I would like to install this DS but I failed searching package `lima-camera-photonicscience-tango`, probably because I have not the good package name.

Here are the steps I followed:
```
conda config --env --add channels conda-forge
conda config --env --append channels default
conda config --env --append channels esrf-bcu
conda config --env --append channels tango-controls
conda install lima-camera-photonicscience-tango
```
Could you give me the name of the package to install ?

Regards.

**Comment by PhilLAL** [comment]
From a answers of @sdebionne and @claustre (thanks to them), the package name `lima-camera-photonicscience-tango` is correct.

**Comment by laurent-claustre** [comment]
Hi @PhilLAL , the main issue with the photonicscience lima conda package is that we do have yet package the SDK, I let @sdebionne telling more about this issue

**Comment by sdebionne** [comment]
Hi @PhilLAL, I have a package ready that needs to be tested (but I dont have detector handy), it's on our `esrf-bcu-devel` (mind the `devel`) channel. I would appreciate any feedback...
